name: Verify HealthCheck

on:
  [push]

jobs:
  check_health:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v4
      with:
        url: https://full-stack-open-pokedex-fki4.onrender.com/health
        follow-redirect: false
        max-attempts: 3
        retry-delay: 5s
        retry-all: false