name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

  date_and_dir_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Date
        run: |
          echo date
      - name: Dir
        run: |
          echo ls -l